---
- name: User management playbook
  hosts: all
  become: yes
  vars:
    ansible_become_password: "{{ sudo_password }}"
  tasks:
    - name: Ensure users are present
      ansible.builtin.user:
        name: "{{ item.username }}"
        comment: "{{ item.first_name }} {{ item.last_name }}"
        password: "{{ item.password | password_hash('sha512') }}"
        groups: "{{ item.groups }}"
        append: yes
        state: present
      loop:
        - { username: 'komar', first_name: 'Kais', last_name: 'Omar', password: 'Admin', groups: 'sudo' }
        - { username: 'arun', first_name: 'Arun', last_name: 'Krishna', password: 'Admin', groups: 'users' }
        - { username: 'pmane', first_name: 'pratik', last_name: 'mane', password: 'Admin', groups: 'sudo' }
        - { username: 'sai', first_name: 'sai', last_name: 'nishanth', password: 'Admin', groups: 'audit' }

    # The following task is an example of removing a user
    - name: Ensure a user is removed
      ansible.builtin.user:
        name: "unnecessary_user"
        state: absent
      when: inventory_hostname in groups['group_to_remove_user']
